version: '3.8'

services:
  monolith:
    image: monolith:local
    build:
      context: ./services/monolith
    container_name: monolith
    volumes:
      - ./services/monolith/uploads:/data/uploads
    networks:
      - file-net
    ports:
      - "8080:8080"
    environment:
      # Point to your local Prometheus and Grafana
      - PROMETHEUS_URL=http://host.docker.internal:9090
      - GRAFANA_URL=http://host.docker.internal:3000

networks:
  file-net:
    driver: bridge
