global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-service"
    static_configs:
      - targets: ["api-service:5000"]

  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:5001"]

  - job_name: "storage-service"
    static_configs:
      - targets: ["storage-service:5002"]
