global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kubernetes-services'
    static_configs:
      - targets: ['api-service:5000','auth-service:5001','storage-service:5002','monolith:8080']
    metrics_path: /metrics
