apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: file-share-services
  namespace: file-share
  labels: { release: prometheus }
spec:
  selector:
    matchLabels:
      app: api-service
  endpoints:
    - path: /metrics
      port: http
