apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels: { app: auth-service }
spec:
  replicas: 1
  selector: { matchLabels: { app: auth-service } }
  template:
    metadata:
      labels: { app: auth-service }
    spec:
      containers:
      - name: auth
        image: your-registry/auth-service:latest
        ports: [{ containerPort: 5001 }]
        resources:
          requests: { cpu: "50m", memory: "64Mi" }
          limits: { cpu: "200m", memory: "256Mi" }
